services:

  sqldatawallet:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    container_name: sqldatawallet
    user: root
    environment:
      - SA_PASSWORD
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "5445:1433"
    volumes:
      - wallet-sqldatawallet:/var/opt/mssql/data/
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 1s


  wallet-api:
    image: ${DOCKER_REGISTRY:-wallet}/wallet.api:${TAG:-latest}
    container_name: wallet-api
    build:
      context: .
      dockerfile: src/Wallet/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT
      - ConnectionStrings__TemplateDatabase=${WALLET_DB_CONNECTION}
    ports:
      - "5101:80"
      - "50002:50001"

volumes:
  wallet-sqldatawallet:
